
#include <pybind11/pybind11.h>
#include <pybind11/eigen.h>
#include <pcl/point_types.h>

namespace py = pybind11;
using namespace pybind11::literals;

void define2dClasses0(py::module &);
void definebaseClasses0(py::module &);
void definebaseClasses1(py::module &);
void definebaseClasses2(py::module &);
void definebaseClasses3(py::module &);
void definebaseClasses4(py::module &);
void definebaseClasses5(py::module &);
void definebaseClasses6(py::module &);
void definebaseClasses7(py::module &);
void definecommonClasses0(py::module &);
void definecommonClasses1(py::module &);
void definecommonClasses2(py::module &);
void definecommonClasses3(py::module &);
void definecommonClasses4(py::module &);
void definecommonClasses5(py::module &);
void definecommonClasses6(py::module &);
void definecommonClasses7(py::module &);
void definecommonClasses8(py::module &);
void definecommonClasses9(py::module &);
void definefeaturesClasses0(py::module &);
void definefeaturesClasses1(py::module &);
void definefeaturesClasses10(py::module &);
void definefeaturesClasses11(py::module &);
void definefeaturesClasses12(py::module &);
void definefeaturesClasses13(py::module &);
void definefeaturesClasses14(py::module &);
void definefeaturesClasses15(py::module &);
void definefeaturesClasses16(py::module &);
void definefeaturesClasses17(py::module &);
void definefeaturesClasses18(py::module &);
void definefeaturesClasses19(py::module &);
void definefeaturesClasses2(py::module &);
void definefeaturesClasses20(py::module &);
void definefeaturesClasses3(py::module &);
void definefeaturesClasses4(py::module &);
void definefeaturesClasses5(py::module &);
void definefeaturesClasses6(py::module &);
void definefeaturesClasses7(py::module &);
void definefeaturesClasses8(py::module &);
void definefeaturesClasses9(py::module &);
void definefiltersClasses0(py::module &);
void definefiltersClasses1(py::module &);
void definefiltersClasses10(py::module &);
void definefiltersClasses11(py::module &);
void definefiltersClasses12(py::module &);
void definefiltersClasses13(py::module &);
void definefiltersClasses14(py::module &);
void definefiltersClasses2(py::module &);
void definefiltersClasses3(py::module &);
void definefiltersClasses4(py::module &);
void definefiltersClasses5(py::module &);
void definefiltersClasses6(py::module &);
void definefiltersClasses7(py::module &);
void definefiltersClasses8(py::module &);
void definefiltersClasses9(py::module &);
void definegeometryClasses0(py::module &);
void definegeometryClasses1(py::module &);
void definegeometryClasses2(py::module &);
void definegeometryClasses3(py::module &);
void definegeometryClasses4(py::module &);
void defineioClasses0(py::module &);
void defineioClasses1(py::module &);
void defineioClasses10(py::module &);
void defineioClasses11(py::module &);
void defineioClasses2(py::module &);
void defineioClasses3(py::module &);
void defineioClasses4(py::module &);
void defineioClasses5(py::module &);
void defineioClasses6(py::module &);
void defineioClasses7(py::module &);
void defineioClasses8(py::module &);
void defineioClasses9(py::module &);
void definekdtreeClasses0(py::module &);
void definekdtreeClasses1(py::module &);
void defineoctreeClasses0(py::module &);
void defineoctreeClasses1(py::module &);
void defineoctreeClasses2(py::module &);
void defineoctreeClasses3(py::module &);
void defineoctreeClasses4(py::module &);
void definerecognitionClasses0(py::module &);
void definerecognitionClasses1(py::module &);
void definerecognitionClasses2(py::module &);
void definerecognitionClasses3(py::module &);
void definerecognitionClasses4(py::module &);
void definerecognitionClasses5(py::module &);
void definerecognitionClasses6(py::module &);
void definerecognitionClasses7(py::module &);
void definerecognitionClasses8(py::module &);
void definerecognitionClasses9(py::module &);
void definesample_consensusClasses0(py::module &);
void definesample_consensusClasses1(py::module &);
void definesample_consensusClasses10(py::module &);
void definesample_consensusClasses11(py::module &);
void definesample_consensusClasses12(py::module &);
void definesample_consensusClasses2(py::module &);
void definesample_consensusClasses3(py::module &);
void definesample_consensusClasses4(py::module &);
void definesample_consensusClasses5(py::module &);
void definesample_consensusClasses6(py::module &);
void definesample_consensusClasses7(py::module &);
void definesample_consensusClasses8(py::module &);
void definesample_consensusClasses9(py::module &);
void definesearchClasses0(py::module &);
void definesearchClasses1(py::module &);
void definesearchClasses2(py::module &);
void definesegmentationClasses0(py::module &);
void definesegmentationClasses1(py::module &);
void definesegmentationClasses2(py::module &);
void definesegmentationClasses3(py::module &);
void definesegmentationClasses4(py::module &);
void definesegmentationClasses5(py::module &);
void definesegmentationClasses6(py::module &);
void definesegmentationClasses7(py::module &);
void definestereoClasses0(py::module &);
void definestereoClasses1(py::module &);
void definesurfaceClasses0(py::module &);
void definesurfaceClasses1(py::module &);
void definesurfaceClasses10(py::module &);
void definesurfaceClasses2(py::module &);
void definesurfaceClasses3(py::module &);
void definesurfaceClasses4(py::module &);
void definesurfaceClasses5(py::module &);
void definesurfaceClasses6(py::module &);
void definesurfaceClasses7(py::module &);
void definesurfaceClasses8(py::module &);
void definesurfaceClasses9(py::module &);
void definetrackingClasses0(py::module &);
void definetrackingClasses1(py::module &);
void definetrackingClasses2(py::module &);
void definetrackingClasses3(py::module &);
void definetrackingClasses4(py::module &);
void definetrackingClasses5(py::module &);
void definevisualizationClasses0(py::module &);
void definevisualizationClasses1(py::module &);
void definevisualizationClasses2(py::module &);
void definevisualizationClasses3(py::module &);
void definevisualizationClasses4(py::module &);
void definevisualizationClasses5(py::module &);
void definevisualizationClasses6(py::module &);
void definevisualizationClasses7(py::module &);

void defineClasses(py::module &m) {
    define2dClasses0(m);
    definebaseClasses0(m);
    definebaseClasses1(m);
    definebaseClasses2(m);
    definebaseClasses3(m);
    definebaseClasses4(m);
    definebaseClasses5(m);
    definebaseClasses6(m);
    definebaseClasses7(m);
    definecommonClasses0(m);
    definecommonClasses1(m);
    definecommonClasses2(m);
    definecommonClasses3(m);
    definecommonClasses4(m);
    definecommonClasses5(m);
    definecommonClasses6(m);
    definecommonClasses7(m);
    definecommonClasses8(m);
    definecommonClasses9(m);
    definefeaturesClasses0(m);
    definefeaturesClasses1(m);
    definefeaturesClasses10(m);
    definefeaturesClasses11(m);
    definefeaturesClasses12(m);
    definefeaturesClasses13(m);
    definefeaturesClasses14(m);
    definefeaturesClasses15(m);
    definefeaturesClasses16(m);
    definefeaturesClasses17(m);
    definefeaturesClasses18(m);
    definefeaturesClasses19(m);
    definefeaturesClasses2(m);
    definefeaturesClasses20(m);
    definefeaturesClasses3(m);
    definefeaturesClasses4(m);
    definefeaturesClasses5(m);
    definefeaturesClasses6(m);
    definefeaturesClasses7(m);
    definefeaturesClasses8(m);
    definefeaturesClasses9(m);
    definefiltersClasses0(m);
    definefiltersClasses1(m);
    definefiltersClasses10(m);
    definefiltersClasses11(m);
    definefiltersClasses12(m);
    definefiltersClasses13(m);
    definefiltersClasses14(m);
    definefiltersClasses2(m);
    definefiltersClasses3(m);
    definefiltersClasses4(m);
    definefiltersClasses5(m);
    definefiltersClasses6(m);
    definefiltersClasses7(m);
    definefiltersClasses8(m);
    definefiltersClasses9(m);
    definegeometryClasses0(m);
    definegeometryClasses1(m);
    definegeometryClasses2(m);
    definegeometryClasses3(m);
    definegeometryClasses4(m);
    defineioClasses0(m);
    defineioClasses1(m);
    defineioClasses10(m);
    defineioClasses11(m);
    defineioClasses2(m);
    defineioClasses3(m);
    defineioClasses4(m);
    defineioClasses5(m);
    defineioClasses6(m);
    defineioClasses7(m);
    defineioClasses8(m);
    defineioClasses9(m);
    definekdtreeClasses0(m);
    definekdtreeClasses1(m);
    defineoctreeClasses0(m);
    defineoctreeClasses1(m);
    defineoctreeClasses2(m);
    defineoctreeClasses3(m);
    defineoctreeClasses4(m);
    definerecognitionClasses0(m);
    definerecognitionClasses1(m);
    definerecognitionClasses2(m);
    definerecognitionClasses3(m);
    definerecognitionClasses4(m);
    definerecognitionClasses5(m);
    definerecognitionClasses6(m);
    definerecognitionClasses7(m);
    definerecognitionClasses8(m);
    definerecognitionClasses9(m);
    definesample_consensusClasses0(m);
    definesample_consensusClasses1(m);
    definesample_consensusClasses10(m);
    definesample_consensusClasses11(m);
    definesample_consensusClasses12(m);
    definesample_consensusClasses2(m);
    definesample_consensusClasses3(m);
    definesample_consensusClasses4(m);
    definesample_consensusClasses5(m);
    definesample_consensusClasses6(m);
    definesample_consensusClasses7(m);
    definesample_consensusClasses8(m);
    definesample_consensusClasses9(m);
    definesearchClasses0(m);
    definesearchClasses1(m);
    definesearchClasses2(m);
    definesegmentationClasses0(m);
    definesegmentationClasses1(m);
    definesegmentationClasses2(m);
    definesegmentationClasses3(m);
    definesegmentationClasses4(m);
    definesegmentationClasses5(m);
    definesegmentationClasses6(m);
    definesegmentationClasses7(m);
    definestereoClasses0(m);
    definestereoClasses1(m);
    definesurfaceClasses0(m);
    definesurfaceClasses1(m);
    definesurfaceClasses10(m);
    definesurfaceClasses2(m);
    definesurfaceClasses3(m);
    definesurfaceClasses4(m);
    definesurfaceClasses5(m);
    definesurfaceClasses6(m);
    definesurfaceClasses7(m);
    definesurfaceClasses8(m);
    definesurfaceClasses9(m);
    definetrackingClasses0(m);
    definetrackingClasses1(m);
    definetrackingClasses2(m);
    definetrackingClasses3(m);
    definetrackingClasses4(m);
    definetrackingClasses5(m);
    definevisualizationClasses0(m);
    definevisualizationClasses1(m);
    definevisualizationClasses2(m);
    definevisualizationClasses3(m);
    definevisualizationClasses4(m);
    definevisualizationClasses5(m);
    definevisualizationClasses6(m);
    definevisualizationClasses7(m);
}