
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
#include <pybind11/eigen.h>
#include <pcl/point_types.h>

namespace py = pybind11;
using namespace pybind11::literals;

PYBIND11_DECLARE_HOLDER_TYPE(T, boost::shared_ptr<T>);
#include "../../make_opaque_vectors.hpp"

#include <pcl/common/distances.h>



void defineCommonDistancesFunctions1(py::module &m) {
    m.def("lineToLineSegment", py::overload_cast<const Eigen::VectorXf &, const Eigen::VectorXf &, Eigen::Vector4f &, Eigen::Vector4f &> (&pcl::lineToLineSegment), "line_a"_a, "line_b"_a, "pt1_seg"_a, "pt2_seg"_a);
    m.def("sqrPointToLineDistance", py::overload_cast<const Eigen::Vector4f &, const Eigen::Vector4f &, const Eigen::Vector4f &> (&pcl::sqrPointToLineDistance), "pt"_a, "line_pt"_a, "line_dir"_a);
    m.def("sqrPointToLineDistance", py::overload_cast<const Eigen::Vector4f &, const Eigen::Vector4f &, const Eigen::Vector4f &, const double> (&pcl::sqrPointToLineDistance), "pt"_a, "line_pt"_a, "line_dir"_a, "sqr_length"_a);
}

template <typename PointT>
void defineCommonDistancesFunctions2(py::module &m) {
    m.def("getMaxSegment", py::overload_cast<const pcl::PointCloud<PointT> &, PointT &, PointT &> (&pcl::getMaxSegment<PointT>), "cloud"_a, "pmin"_a, "pmax"_a);
    m.def("getMaxSegment", py::overload_cast<const pcl::PointCloud<PointT> &, const std::vector<int> &, PointT &, PointT &> (&pcl::getMaxSegment<PointT>), "cloud"_a, "indices"_a, "pmin"_a, "pmax"_a);
}

template<typename PointType1, typename PointType2>
void defineCommonDistancesFunctions3(py::module &m) {
    m.def("euclideanDistance", py::overload_cast<const PointType1 &, const PointType2 &> (&pcl::euclideanDistance<PointType1, PointType2>), "p1"_a, "p2"_a);
    m.def("squaredEuclideanDistance", py::overload_cast<const PointType1 &, const PointType2 &> (&pcl::squaredEuclideanDistance<PointType1, PointType2>), "p1"_a, "p2"_a);
}

void defineCommonDistancesFunctions(py::module &m) {
    defineCommonDistancesFunctions1(m);
    defineCommonDistancesFunctions2<pcl::PointXYZ>(m);
    defineCommonDistancesFunctions2<pcl::PointXYZI>(m);
    defineCommonDistancesFunctions2<pcl::PointXYZL>(m);
    defineCommonDistancesFunctions2<pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions2<pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions2<pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions2<pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions2<pcl::InterestPoint>(m);
    defineCommonDistancesFunctions2<pcl::PointNormal>(m);
    defineCommonDistancesFunctions2<pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions2<pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions2<pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions2<pcl::PointWithRange>(m);
    defineCommonDistancesFunctions2<pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions2<pcl::PointWithScale>(m);
    defineCommonDistancesFunctions2<pcl::PointSurfel>(m);
    defineCommonDistancesFunctions2<pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZ, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZI, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZL, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBA, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGB, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBL, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZHSV, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::InterestPoint, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointNormal, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZRGBNormal, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZINormal, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointXYZLNormal, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointWithRange, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointWithViewpoint, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointWithScale, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointSurfel, pcl::PointDEM>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointXYZ>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointXYZI>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointXYZL>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointXYZRGBA>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointXYZRGB>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointXYZRGBL>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointXYZHSV>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::InterestPoint>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointXYZRGBNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointXYZINormal>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointXYZLNormal>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointWithRange>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointWithViewpoint>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointWithScale>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointSurfel>(m);
    defineCommonDistancesFunctions3<pcl::PointDEM, pcl::PointDEM>(m);
}

void defineCommonDistancesClasses(py::module &sub_module) {
    defineCommonDistancesFunctions(sub_module);
}